### PR TITLE
Fixes mobile navigation menus

### PR DESCRIPTION
**Pull request by heatherkolf**

### CODE REVIEW

**Comment by axamei** [comment]
@heatherkolf It looks like the videos in the bio page are overflowing within the bounds of a smaller viewport (mobile). You might want to add a container (in this example with a class of "embed-container") for those videos and try this responsive video embed styling:

```@media (max-width: 375px) {
  .embed-container {
    position: relative;
    padding-bottom: 56.25%;
    margin-bottom: 1em;
    height: 0;
    overflow: hidden;
    max-width: 100%;
  }

  .embed-container iframe,
  .embed-container object,
  .embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }
}```

**Comment by heatherkolf** [comment]
Hello @axamei,
I just created the container and inserted the css, which does fix the overflow problem on mobile, so thank you!  But now only one video shows up on the mobile bio page...maybe I did this incorrectly?  I will be googling, but if you have any ideas for how to show all three videos, please let me know!
Thanks,
Heather

**Comment by axamei** [comment]
@heatherkolf you can nest the embed video styling in a media query. if you use max-width as your query target, those styles should be limited to smaller screens.

**Comment by heatherkolf** [comment]
@axamei I think I did this like you said...the embed video style is nested within a media query (in my second commit).  But for some reason, all three videos appear on the desktop version (which I want), but the mobile version only shows one video (instead of showing 3 stacked videos):

Desktop (good):
screen shot 2018-12-08 at 10 21 14 pm

Mobile (not so good?):
screen shot 2018-12-08 at 10 20 38 pm

I'm not sure where the other 2 videos have gone on the mobile version...any ideas?

Thanks!
Heather


Media Queries:

@media screen and (max-width: 320px) {

  .main-navigation li {
    font-size: 1.5em;
    float: left;
    margin-right: 0px;
    padding-top: 5px;
  }

  .main-navigation li a,
  .dropbtn {
    display: inline;
    padding: 0px;
    padding-right: 20px;
    padding-left: 20px;
  }

  .main-navigation .dropdown-content a {
    display: block;
    padding-bottom: 10px;
    text-align: left;
    padding-left: 2px;
    padding-right: 100px;
  }

  .dropdown-content {
    font-size: .6em;
    display: none;
  }

  .embed-container {
    position: relative;
    padding-bottom: 56.25%;
    margin-bottom: 1em;
    height: 0;
    overflow: hidden;
    max-width: 100%;
    text-align: center;
  }

  .embed-container iframe,
  .embed-container object,
  .embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  .footer li {
    font-size: 1em;
    margin-right: 0px;
    margin-left: 0px;
    width: 30%;
    margin-left: -30px;
  }
}

@media screen and (max-width: 768px) {

  .main-navigation li {
    font-size: 1.5em;
    float: left;
    margin-right: 0px;
    padding-top: 5px;
  }

  .main-navigation li a,
  .dropbtn {
    display: inline;
    padding: 0px;
    padding-right: 20px;
    padding-left: 20px;
  }

  .main-navigation .dropdown-content a {
    display: block;
    padding-bottom: 10px;
    text-align: left;
    padding-left: 2px;
    padding-right: 100px;
  }

  .dropdown-content {
    font-size: .6em;
    display: none;
  }

  .embed-container {
    position: relative;
    padding-bottom: 56.25%;
    margin-bottom: 1em;
    height: 0;
    overflow: hidden;
    max-width: 100%;
    text-align: center;
  }

  .embed-container iframe,
  .embed-container object,
  .embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
  }

  .footer li {
    font-size: 1em;
    margin-right: 0px;
    margin-left: 0px;
    width: 30%;
    margin-left: -30px;
  }
}

**Pull request merged**
